
linter:
  image: node:latest
  cache:
    paths:
      - node_modules
  script:
    - yarn
    - yarn submodule
    - yarn lint:ts
    - yarn lint:css

# cypress:
#   image: cypress/base:10
#   stage: test
#   cache:
#     paths:
#       - .npm
#       - cache/Cypress
#       - node_modules
#   script:
#     - yarn
#     - yarn build
#     - yarn cy:verify
