stages:
  - test

linter:
  image: node:latest
  stage: test
  cache:
    paths:
      - node_modules
  script:
    - yarn
    - yarn submodule
    - yarn lint:ts
    - yarn lint:css

cypress:
  image: 
    name: cypress/included:8.5.0
    entrypoint: [""]
  stage: test
  cache:
    paths:
      - .npm
      - cache/Cypress
      - node_modules
  script:
    - yarn
    - yarn cy:verify
    - yarn cy:ci
