export function combineToChart(mockData) {

  return mockData.map((dataItem) => ({
    angle: parseFloat(dataItem.portfolioPerc),
    label: dataItem.symbol,
    realValue: parseFloat(dataItem.portfolioPerc),
    labelCurrency: dataItem.exchange
  }))
}

export function combineToBarChart(dataForChart) {

  const newDataForBarChart = dataForChart.map((dataItem) => ({
    x: dataItem.symbol,
    y: parseFloat(parseFloat(dataItem.portfolioPerc).toFixed(2))
  }))

  console.log('newDataForBarChart', newDataForBarChart);

  return newDataForBarChart
}

export const PieChartMockFirst = [
  {
    name: 'ETH',
    value: 0.82562342,
  },
  {
    name: 'BTC',
    value: 1.62562342,
  },
  {
    name: 'LTC',
    value: 2.32562342,
  },
]

export const PieChartMockSecond = [
  {
    name: 'XPR',
    value: 2.5213123,
  },
  {
    name: 'BTC',
    value: 3.123123123,
  },
  {
    name: 'LTC',
    value: 8.12312312,
  },
]

export const mockTableData = [
  {
    exchange: 'Bitrex',
    symbol: 'ETH',
    price: 12950,
    mock: true
  },
  {
    exchange: 'GDAX',
    symbol: 'ETH',
    price: 10000,
    mock: true
  },
  {
    exchange: 'Binance',
    symbol: 'LTC',
    price: 2000,
    mock: true
  },
  {
    exchange: 'Binance',
    symbol: 'XRP',
    price: 5000,
    mock: true
  },
  {
    exchange: 'Binance',
    symbol: 'PCI',
    price: 2000,
    mock: true
  },
  {
    exchange: 'Binance',
    symbol: 'LTU',
    price: 5000,
    mock: true
  },
  {
    exchange: 'Binance',
    symbol: 'PKI',
    price: 2000,
    mock: true
  },
  {
    exchange: 'Binance',
    symbol: 'DKI',
    price: 5000,
    mock: true
  },
]

export const exchangeOptions = [
  { label: '1BTCXE', value: '1BTCXE' },
  { label: '1Broker', value: '1Broker' },
  { label: 'ACX', value: 'ACX' },
  { label: 'ANXPro', value: 'ANXPro' },
  { label: 'Allcoin', value: 'Allcoin' },
  { label: 'BL3P', value: 'BL3P' },
  { label: 'BTC Markets', value: 'BTC Markets' },
  { label: 'BTC Trade UA', value: 'BTC Trade UA' },
  { label: 'BTCChina', value: 'BTCChina' },
  { label: 'BTCExchange', value: 'BTCExchange' },
  { label: 'BTCTurk', value: 'BTCTurk' },
  { label: 'BTCX', value: 'BTCX' },
  { label: 'BX.in.th', value: 'BX.in.th' },
  { label: 'Bibox', value: 'Bibox' },
  { label: 'Binance', value: 'Binance' },
  { label: 'Bit-Z', value: 'Bit-Z' },
  { label: 'Bit2C', value: 'Bit2C' },
  { label: 'BitBay', value: 'BitBay' },
  { label: 'BitMEX', value: 'BitMEX' },
  { label: 'BitMarket', value: 'BitMarket' },
  { label: 'Bitfinex', value: 'Bitfinex' },
  { label: 'Bitfinex v2', value: 'Bitfinex v2' },
  { label: 'Bithumb', value: 'Bithumb' },
  { label: 'Bitlish', value: 'Bitlish' },
  { label: 'Bitso', value: 'Bitso' },
  { label: 'Bitstamp', value: 'Bitstamp' },
  { label: 'Bitstamp v1', value: 'Bitstamp v1' },
  { label: 'Bittrex', value: 'Bittrex' },
  { label: 'Bleutrade', value: 'Bleutrade' },
  { label: 'Braziliex', value: 'Braziliex' },
  { label: 'BtcBox', value: 'BtcBox' },
  { label: 'BtcTrade.im', value: 'BtcTrade.im' },
  { label: 'C-CEX', value: 'C-CEX' },
  { label: 'CEX.IO', value: 'CEX.IO' },
  { label: 'CHBTC', value: 'CHBTC' },
  { label: 'COBINHOOD', value: 'COBINHOOD' },
  { label: 'ChileBit', value: 'ChileBit' },
  { label: 'CoinEgg', value: 'CoinEgg' },
  { label: 'CoinEx', value: 'CoinEx' },
  { label: 'CoinExchange', value: 'CoinExchange' },
  { label: 'CoinMarketCap', value: 'CoinMarketCap' },
  { label: 'CoinMate', value: 'CoinMate' },
  { label: 'CoinOne', value: 'CoinOne' },
  { label: 'CoinSpot', value: 'CoinSpot' },
  { label: 'CoinTiger', value: 'CoinTiger' },
  { label: 'Coingi', value: 'Coingi' },
  { label: 'Coinsecure', value: 'Coinsecure' },
  { label: 'CoolCoin', value: 'CoolCoin' },
  { label: 'Cryptopia', value: 'Cryptopia' },
  { label: 'DSX', value: 'DSX' },
  { label: 'EXMO', value: 'EXMO' },
  { label: 'EXX', value: 'EXX' },
  { label: 'Ethfinex', value: 'Ethfinex' },
  { label: 'FYB-SE', value: 'FYB-SE' },
  { label: 'FYB-SG', value: 'FYB-SG' },
  { label: 'FoxBit', value: 'FoxBit' },
  { label: 'GDAX', value: 'GDAX' },
  { label: 'Gate.io', value: 'Gate.io' },
  { label: 'Gatecoin', value: 'Gatecoin' },
  { label: 'Gemini', value: 'Gemini' },
  { label: 'GetBTC', value: 'GetBTC' },
  { label: 'HADAX', value: 'HADAX' },
  { label: 'HitBTC', value: 'HitBTC' },
  { label: 'HitBTC v2', value: 'HitBTC v2' },
  { label: 'Huobi', value: 'Huobi' },
  { label: 'Huobi CNY', value: 'Huobi CNY' },
  { label: 'Huobi Pro', value: 'Huobi Pro' },
  { label: 'ICE3X', value: 'ICE3X' },
  { label: 'INDODAX', value: 'INDODAX' },
  { label: 'Independent Reserve', value: 'Independent Reserve' },
  { label: 'Kraken', value: 'Kraken' },
  { label: 'Kucoin', value: 'Kucoin' },
  { label: 'Kuna', value: 'Kuna' },
  { label: 'LBank', value: 'LBank' },
  { label: 'LakeBTC', value: 'LakeBTC' },
  { label: 'Liqui', value: 'Liqui' },
  { label: 'LiveCoin', value: 'LiveCoin' },
  { label: 'Lykke', value: 'Lykke' },
  { label: 'Mercado Bitcoin', value: 'Mercado Bitcoin' },
  { label: 'MixCoins', value: 'MixCoins' },
  { label: 'NegocieCoins', value: 'NegocieCoins' },
  { label: 'Novaexchange', value: 'Novaexchange' },
  { label: 'OKCoin CNY', value: 'OKCoin CNY' },
  { label: 'OKCoin USD', value: 'OKCoin USD' },
  { label: 'OKEX', value: 'OKEX' },
  { label: 'Paymium', value: 'Paymium' },
  { label: 'Poloniex', value: 'Poloniex' },
  { label: 'QRYPTOS', value: 'QRYPTOS' },
  { label: 'QUOINEX', value: 'QUOINEX' },
  { label: 'QuadrigaCX', value: 'QuadrigaCX' },
  { label: 'SouthXchange', value: 'SouthXchange' },
  { label: 'SurBitcoin', value: 'SurBitcoin' },
  { label: 'TheRockTrading', value: 'TheRockTrading' },
  { label: 'TideBit', value: 'TideBit' },
  { label: 'Tidex', value: 'Tidex' },
  { label: 'UrduBit', value: 'UrduBit' },
  { label: 'VBTC', value: 'VBTC' },
  { label: 'Vaultoro', value: 'Vaultoro' },
  { label: 'VirWoX', value: 'VirWoX' },
  { label: 'WEX', value: 'WEX' },
  { label: 'YUNBI', value: 'YUNBI' },
  { label: 'YoBit', value: 'YoBit' },
  { label: 'ZB', value: 'ZB' },
  { label: 'Zaif', value: 'Zaif' },
  { label: 'bitFlyer', value: 'bitFlyer' },
  { label: 'bitbank', value: 'bitbank' },
  { label: 'bitkk', value: 'bitkk' },
  { label: 'coinbase', value: 'coinbase' },
  { label: 'coincheck', value: 'coincheck' },
  { label: 'coinfloor', value: 'coinfloor' },
  { label: 'coinnest', value: 'coinnest' },
  { label: 'flowBTC', value: 'flowBTC' },
  { label: 'itBit', value: 'itBit' },
  { label: 'jubi.com', value: 'jubi.com' },
  { label: 'luno', value: 'luno' },
  { label: 'xBTCe', value: 'xBTCe' }
]

export const coinsOptions = [
  { label: 'BCH', value: 'BCH' },
  { label: 'BTC', value: 'BTC' },
  { label: 'ETH', value: 'ETH' },
  { label: 'LTC', value: 'LTC' },
  { label: 'BNB', value: 'BNB' },
  { label: 'NEO', value: 'NEO' },
  { label: 'QTUM', value: 'QTUM' },
  { label: 'EOS', value: 'EOS' },
  { label: 'SNT', value: 'SNT' },
  { label: 'BNT', value: 'BNT' },
  { label: 'BCC', value: 'BCC' },
  { label: 'GAS', value: 'GAS' },
  { label: 'HSR', value: 'HSR' },
  { label: 'OAX', value: 'OAX' },
  { label: 'DNT', value: 'DNT' },
  { label: 'MCO', value: 'MCO' },
  { label: 'ICN', value: 'ICN' },
  { label: 'WTC', value: 'WTC' },
  { label: 'LRC', value: 'LRC' },
  { label: 'OMG', value: 'OMG' },
  { label: 'ZRX', value: 'ZRX' },
  { label: 'STRAT', value: 'STRAT' },
  { label: 'SNGLS', value: 'SNGLS' },
  { label: 'BQX', value: 'BQX' },
  { label: 'KNC', value: 'KNC' },
  { label: 'FUN', value: 'FUN' },
  { label: 'SNM', value: 'SNM' },
  { label: 'MIOTA', value: 'MIOTA' },
  { label: 'LINK', value: 'LINK' },
  { label: 'XVG', value: 'XVG' },
  { label: 'SALT', value: 'SALT' },
  { label: 'MDA', value: 'MDA' },
  { label: 'MTL', value: 'MTL' },
  { label: 'SUB', value: 'SUB' },
  { label: 'ETC', value: 'ETC' },
  { label: 'MTH', value: 'MTH' },
  { label: 'ENG', value: 'ENG' },
  { label: 'ZEC', value: 'ZEC' },
  { label: 'AST', value: 'AST' },
  { label: 'DASH', value: 'DASH' },
  { label: 'BTG', value: 'BTG' },
  { label: 'EVX', value: 'EVX' },
  { label: 'REQ', value: 'REQ' },
  { label: 'VIB', value: 'VIB' },
  { label: 'TRX', value: 'TRX' },
  { label: 'POWR', value: 'POWR' },
  { label: 'ARK', value: 'ARK' },
  { label: 'YOYO', value: 'YOYO' },
  { label: 'XRP', value: 'XRP' },
  { label: 'MOD', value: 'MOD' },
  { label: 'ENJ', value: 'ENJ' },
  { label: 'STORJ', value: 'STORJ' },
  { label: 'VEN', value: 'VEN' },
  { label: 'KMD', value: 'KMD' },
  { label: 'NULS', value: 'NULS' },
  { label: 'RCN', value: 'RCN' },
  { label: 'RDN', value: 'RDN' },
  { label: 'XMR', value: 'XMR' },
  { label: 'DLT', value: 'DLT' },
  { label: 'AMB', value: 'AMB' },
  { label: 'BAT', value: 'BAT' },
  { label: 'BCPT', value: 'BCPT' },
  { label: 'ARN', value: 'ARN' },
  { label: 'GVT', value: 'GVT' },
  { label: 'CDT', value: 'CDT' },
  { label: 'GXS', value: 'GXS' },
  { label: 'POE', value: 'POE' },
  { label: 'QSP', value: 'QSP' },
  { label: 'BTS', value: 'BTS' },
  { label: 'XZC', value: 'XZC' },
  { label: 'LSK', value: 'LSK' },
  { label: 'TNT', value: 'TNT' },
  { label: 'FUEL', value: 'FUEL' },
  { label: 'MANA', value: 'MANA' },
  { label: 'BCD', value: 'BCD' },
  { label: 'DGD', value: 'DGD' },
  { label: 'ADX', value: 'ADX' },
  { label: 'ADA', value: 'ADA' },
  { label: 'PPT', value: 'PPT' },
  { label: 'CMT', value: 'CMT' },
  { label: 'XLM', value: 'XLM' },
  { label: 'CND', value: 'CND' },
  { label: 'LEND', value: 'LEND' },
  { label: 'WABI', value: 'WABI' },
  { label: 'TNB', value: 'TNB' },
  { label: 'WAVES', value: 'WAVES' },
  { label: 'GTO', value: 'GTO' },
  { label: 'ICX', value: 'ICX' },
  { label: 'OST', value: 'OST' },
  { label: 'ELF', value: 'ELF' },
  { label: 'AION', value: 'AION' },
  { label: 'NEBL', value: 'NEBL' },
  { label: 'BRD', value: 'BRD' },
  { label: 'EDO', value: 'EDO' },
  { label: 'WINGS', value: 'WINGS' },
  { label: 'NAV', value: 'NAV' },
  { label: 'LUN', value: 'LUN' },
  { label: 'TRIG', value: 'TRIG' },
  { label: 'APPC', value: 'APPC' },
  { label: 'VIBE', value: 'VIBE' },
  { label: 'RLC', value: 'RLC' },
  { label: 'INS', value: 'INS' },
  { label: 'PIVX', value: 'PIVX' },
  { label: 'IOST', value: 'IOST' },
  { label: 'CHAT', value: 'CHAT' },
  { label: 'STEEM', value: 'STEEM' },
  { label: 'NANO', value: 'NANO' },
  { label: 'VIA', value: 'VIA' },
  { label: 'BLZ', value: 'BLZ' },
  { label: 'AE', value: 'AE' },
  { label: 'RPX', value: 'RPX' },
  { label: 'NCASH', value: 'NCASH' },
  { label: 'POA', value: 'POA' },
  { label: 'ZIL', value: 'ZIL' },
  { label: 'ONT', value: 'ONT' },
  { label: 'STORM', value: 'STORM' },
  { label: 'XEM', value: 'XEM' },
  { label: 'WAN', value: 'WAN' },
  { label: 'WPR', value: 'WPR' },
  { label: 'QLC', value: 'QLC' },
  { label: 'SYS', value: 'SYS' },
  { label: 'GRS', value: 'GRS' },
  { label: 'CLOAK', value: 'CLOAK' },
  { label: 'GNT', value: 'GNT' },
  { label: 'LOOM', value: 'LOOM' },
  { label: 'BCN', value: 'BCN' },
  { label: 'REP', value: 'REP' },
  { label: 'TUSD', value: 'TUSD' },
  { label: 'ZEN', value: 'ZEN' },
  { label: 'SKY', value: 'SKY' },
  { label: 'CVC', value: 'CVC' },
  { label: 'THETA', value: 'THETA' },
  { label: 'IOTX', value: 'IOTX' },
  { label: 'QKC', value: 'QKC' },
  { label: 'AGI', value: 'AGI' },
  { label: 'NXS', value: 'NXS' },
  { label: 'DATA', value: 'DATA' },
  { label: 'SC', value: 'SC' },
  { label: 'NPXS', value: 'NPXS' },
  { label: 'KEY', value: 'KEY' },
  { label: 'NAS', value: 'NAS' },
  { label: 'IOTA', value: 'IOTA' },
  { label: 'BTM', value: 'BTM' },
  { label: 'PAY', value: 'PAY' },
  { label: 'DOGE', value: 'DOGE' },
  { label: 'PST', value: 'PST' },
  { label: 'DPY', value: 'DPY' },
  { label: 'STX', value: 'STX' },
  { label: 'KICK', value: 'KICK' },
  { label: 'ZSC', value: 'ZSC' },
  { label: 'CTR', value: 'CTR' },
  { label: 'XTZ', value: 'XTZ' },
  { label: 'GEM', value: 'GEM' },
  { label: 'RFR', value: 'RFR' },
  { label: 'DADI', value: 'DADI' },
  { label: 'ABT', value: 'ABT' },
  { label: 'LEDU', value: 'LEDU' },
  { label: 'MOBI', value: 'MOBI' },
  { label: 'OCN', value: 'OCN' },
  { label: 'ZPT', value: 'ZPT' },
  { label: 'COFI', value: 'COFI' },
  { label: 'JNT', value: 'JNT' },
  { label: 'MTN', value: 'MTN' },
  { label: 'RUFF', value: 'RUFF' },
  { label: 'TNC', value: 'TNC' },
  { label: 'TIO', value: 'TIO' },
  { label: 'BTO', value: 'BTO' },
  { label: 'DDD', value: 'DDD' },
  { label: 'MKR', value: 'MKR' },
  { label: 'DAI', value: 'DAI' },
  { label: 'SMT', value: 'SMT' },
  { label: 'MDT', value: 'MDT' },
  { label: 'DRGN', value: 'DRGN' },
  { label: 'GTC', value: 'GTC' },
  { label: 'DBC', value: 'DBC' },
  { label: 'BNTY', value: 'BNTY' },
  { label: 'BTF', value: 'BTF' },
  { label: 'BIFI', value: 'BIFI' },
  { label: 'MDS', value: 'MDS' },
  { label: 'QASH', value: 'QASH' },
  { label: 'FIL', value: 'FIL' },
  { label: 'SBTC', value: 'SBTC' },
  { label: 'GOD', value: 'GOD' },
  { label: 'BCX', value: 'BCX' },
  { label: 'MFT', value: 'MFT' },
  { label: 'INK', value: 'INK' },
  { label: 'DENT', value: 'DENT' },
  { label: 'MED', value: 'MED' },
  { label: 'BOT', value: 'BOT' },
  { label: 'QBT', value: 'QBT' },
  { label: 'TSL', value: 'TSL' },
  { label: 'GNX', value: 'GNX' },
  { label: 'BCDN', value: 'BCDN' },
  { label: 'SNET', value: 'SNET' },
  { label: 'LLT', value: 'LLT' },
  { label: 'TIPS', value: 'TIPS' },
  { label: 'BU', value: 'BU' },
  { label: 'XMC', value: 'XMC' },
  { label: 'BOE', value: 'BOE' }
]
