export const exchangeOptions = [
  { label: '1BTCXE', value: '1BTCXE' },
  { label: '1Broker', value: '1Broker' },
  { label: 'ACX', value: 'ACX' },
  { label: 'ANXPro', value: 'ANXPro' },
  { label: 'Allcoin', value: 'Allcoin' },
  { label: 'BL3P', value: 'BL3P' },
  { label: 'BTC Markets', value: 'BTC Markets' },
  { label: 'BTC Trade UA', value: 'BTC Trade UA' },
  { label: 'BTCChina', value: 'BTCChina' },
  { label: 'BTCExchange', value: 'BTCExchange' },
  { label: 'BTCTurk', value: 'BTCTurk' },
  { label: 'BTCX', value: 'BTCX' },
  { label: 'BX.in.th', value: 'BX.in.th' },
  { label: 'Bibox', value: 'Bibox' },
  { label: 'Binance', value: 'Binance' },
  { label: 'Bit-Z', value: 'Bit-Z' },
  { label: 'Bit2C', value: 'Bit2C' },
  { label: 'BitBay', value: 'BitBay' },
  { label: 'BitMEX', value: 'BitMEX' },
  { label: 'BitMarket', value: 'BitMarket' },
  { label: 'Bitfinex', value: 'Bitfinex' },
  { label: 'Bitfinex v2', value: 'Bitfinex v2' },
  { label: 'Bithumb', value: 'Bithumb' },
  { label: 'Bitlish', value: 'Bitlish' },
  { label: 'Bitso', value: 'Bitso' },
  { label: 'Bitstamp', value: 'Bitstamp' },
  { label: 'Bitstamp v1', value: 'Bitstamp v1' },
  { label: 'Bittrex', value: 'Bittrex' },
  { label: 'Bleutrade', value: 'Bleutrade' },
  { label: 'Braziliex', value: 'Braziliex' },
  { label: 'BtcBox', value: 'BtcBox' },
  { label: 'BtcTrade.im', value: 'BtcTrade.im' },
  { label: 'C-CEX', value: 'C-CEX' },
  { label: 'CEX.IO', value: 'CEX.IO' },
  { label: 'CHBTC', value: 'CHBTC' },
  { label: 'COBINHOOD', value: 'COBINHOOD' },
  { label: 'ChileBit', value: 'ChileBit' },
  { label: 'CoinEgg', value: 'CoinEgg' },
  { label: 'CoinEx', value: 'CoinEx' },
  { label: 'CoinExchange', value: 'CoinExchange' },
  { label: 'CoinMarketCap', value: 'CoinMarketCap' },
  { label: 'CoinMate', value: 'CoinMate' },
  { label: 'CoinOne', value: 'CoinOne' },
  { label: 'CoinSpot', value: 'CoinSpot' },
  { label: 'CoinTiger', value: 'CoinTiger' },
  { label: 'Coingi', value: 'Coingi' },
  { label: 'Coinsecure', value: 'Coinsecure' },
  { label: 'CoolCoin', value: 'CoolCoin' },
  { label: 'Cryptopia', value: 'Cryptopia' },
  { label: 'DSX', value: 'DSX' },
  { label: 'EXMO', value: 'EXMO' },
  { label: 'EXX', value: 'EXX' },
  { label: 'Ethfinex', value: 'Ethfinex' },
  { label: 'FYB-SE', value: 'FYB-SE' },
  { label: 'FYB-SG', value: 'FYB-SG' },
  { label: 'FoxBit', value: 'FoxBit' },
  { label: 'GDAX', value: 'GDAX' },
  { label: 'Gate.io', value: 'Gate.io' },
  { label: 'Gatecoin', value: 'Gatecoin' },
  { label: 'Gemini', value: 'Gemini' },
  { label: 'GetBTC', value: 'GetBTC' },
  { label: 'HADAX', value: 'HADAX' },
  { label: 'HitBTC', value: 'HitBTC' },
  { label: 'HitBTC v2', value: 'HitBTC v2' },
  { label: 'Huobi', value: 'Huobi' },
  { label: 'Huobi CNY', value: 'Huobi CNY' },
  { label: 'Huobi Pro', value: 'Huobi Pro' },
  { label: 'ICE3X', value: 'ICE3X' },
  { label: 'INDODAX', value: 'INDODAX' },
  { label: 'Independent Reserve', value: 'Independent Reserve' },
  { label: 'Kraken', value: 'Kraken' },
  { label: 'Kucoin', value: 'Kucoin' },
  { label: 'Kuna', value: 'Kuna' },
  { label: 'LBank', value: 'LBank' },
  { label: 'LakeBTC', value: 'LakeBTC' },
  { label: 'Liqui', value: 'Liqui' },
  { label: 'LiveCoin', value: 'LiveCoin' },
  { label: 'Lykke', value: 'Lykke' },
  { label: 'Mercado Bitcoin', value: 'Mercado Bitcoin' },
  { label: 'MixCoins', value: 'MixCoins' },
  { label: 'NegocieCoins', value: 'NegocieCoins' },
  { label: 'Novaexchange', value: 'Novaexchange' },
  { label: 'OKCoin CNY', value: 'OKCoin CNY' },
  { label: 'OKCoin USD', value: 'OKCoin USD' },
  { label: 'OKEX', value: 'OKEX' },
  { label: 'Paymium', value: 'Paymium' },
  { label: 'Poloniex', value: 'Poloniex' },
  { label: 'QRYPTOS', value: 'QRYPTOS' },
  { label: 'QUOINEX', value: 'QUOINEX' },
  { label: 'QuadrigaCX', value: 'QuadrigaCX' },
  { label: 'SouthXchange', value: 'SouthXchange' },
  { label: 'SurBitcoin', value: 'SurBitcoin' },
  { label: 'TheRockTrading', value: 'TheRockTrading' },
  { label: 'TideBit', value: 'TideBit' },
  { label: 'Tidex', value: 'Tidex' },
  { label: 'UrduBit', value: 'UrduBit' },
  { label: 'VBTC', value: 'VBTC' },
  { label: 'Vaultoro', value: 'Vaultoro' },
  { label: 'VirWoX', value: 'VirWoX' },
  { label: 'WEX', value: 'WEX' },
  { label: 'YUNBI', value: 'YUNBI' },
  { label: 'YoBit', value: 'YoBit' },
  { label: 'ZB', value: 'ZB' },
  { label: 'Zaif', value: 'Zaif' },
  { label: 'bitFlyer', value: 'bitFlyer' },
  { label: 'bitbank', value: 'bitbank' },
  { label: 'bitkk', value: 'bitkk' },
  { label: 'coinbase', value: 'coinbase' },
  { label: 'coincheck', value: 'coincheck' },
  { label: 'coinfloor', value: 'coinfloor' },
  { label: 'coinnest', value: 'coinnest' },
  { label: 'flowBTC', value: 'flowBTC' },
  { label: 'itBit', value: 'itBit' },
  { label: 'jubi.com', value: 'jubi.com' },
  { label: 'luno', value: 'luno' },
  { label: 'xBTCe', value: 'xBTCe' }
]
