export const data = {
  industry: [
    { label: 'Smart Contracts', value: 'smartContracts' },
    { label: 'Payments', value: 'payments' },
    { label: 'Blockchain Platform', value: 'blockchain' },
    { label: 'Payment Coin', value: 'paymentCoin' },
    { label: 'Privacy Coin', value: 'privacyCoin' },
    {
      label: 'Third Generation Blockchain',
      value: 'thirdGenerationBlockchain',
    },
    {
      label: 'Scalable Blockchain as a Service Platform',
      value: 'scalableBlockchain',
    },
  ],
  coin: [
    { label: 'USD', value: 'USD' },
    { label: 'BTC', value: 'BTC' },
    { label: 'LTC', value: 'LTC' },
    { label: 'ETH', value: 'ETH' },
    { label: 'DOGE', value: 'DOGE' },
    { label: 'Monero', value: 'Monero' },
  ],
  marketCap: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  averageVolume: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  averageVolumeOnBalance: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  chaikinMoneyFlow: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  changeInDigits: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  changeInPercentage: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  closingPriceAverage: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  simpleMovingAverage: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  one1DayLow: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  one1DayHigh: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  one1HourLow: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  one1HourHigh: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  one1MonthLow: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  one1MonthHigh: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  three3MonthLow: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  three3MonthHigh: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  twelve12MonthLow: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
  twelve12MonthHigh: [
    { label: 'Any', value: null },
    { label: 'Value Below', value: 'valueBelow' },
    { label: 'Value Below or Equal', value: 'valueBelowOrEqual' },
    { label: 'Value Above', value: 'valueAbove' },
    { label: 'Value Above or Equal', value: 'valueAboveOrEqual' },
    { label: 'Value Equals To', value: 'valueEqualsTo' },
    { label: 'Value Not Equal To', value: 'valueNotEqualTo' },
  ],
}
