export const theme = {
  container: { position: 'relative' },
  input: {
    borderBottom: '2px solid rgb(78, 216, 218)',
    boxSizing: 'border-box',
    background: 'transparent',
    borderTop: 'none',
    borderLeft: 'none',
    outline: 'none',
    borderRight: 'none',
    width: '100%',
    fontFamily: 'Roboto',
    fontSize: '16px',
    lineHeight: '24px',
    textAlign: 'left',
    color: '#fff',
    padding: '10px 0',
  },
  suggestionsContainer: {
    display: 'none',
  },
  suggestionsContainerOpen: {
    boxShadow: '0 2px 6px 0 #00000066',
    display: 'block',
    position: 'absolute',
    top: '2.875rem',
    width: '100%',
    backgroundColor: '#393e44',
    fontFamily: 'Roboto',
    color: '#fff',
    fontWeight: '300',
    fontSize: '16px',
    borderBottomLeftRadius: '4px',
    borderBottomRightRadius: '4px',
    zIndex: '2',
  },
  suggestionsList: {
    margin: 0,
    padding: 0,
    listStyleType: 'none',
  },
  suggestion: {
    cursor: 'pointer',
    padding: '10px 20px',
  },
  suggestionHighlighted: {
    backgroundColor: '#292d31',
  },
}
